export const assets: { [filepath: string]: string } = {
  "README.md": `# PDK - Dev Ops

TODO`,
  "approved-licenses.yaml": `---
  - - :permit
    - LicenseRef-.amazon.com.-AmznSL-1.0
  - - :permit
    - AFL-2.0
  - - :permit
    - AFL-3.0
  - - :permit
    - ANTLR-PD
  - - :permit
    - Apache-1.1
  - - :permit
    - Apache-2.0
  - - :permit
    - LLVM-exception
  - - :permit
    - Artistic-1.0
  - - :permit
    - Artistic-1.0-Perl
  - - :permit
    - BSL-1.0
  - - :permit
    - BSD-2-Clause
  - - :permit
    - Simplified BSD
  - - :permit
    - Free BSD
  - - :permit
    - New BSD
  - - :permit
    - BSD-3-Clause
  - - :permit
    - MIT-CMU
  - - :permit
    - MIT-0
  - - :permit
    - Eclipse Public License - v 2.0
  - - :permit
    - EPL 2.0
  - - :permit
    - GPL2 w/ CPE
  - - :permit
    - CDDL License
  - - :permit
    - CDDL + GPLv2 with classpath exception
  - - :permit
    - Eclipse Public License v2.0
  - - :permit
    - CPOL-1.02
  - - :permit
    - CC-BY-2.0
  - - :permit
    - CC-BY-2.5
  - - :permit
    - CC-BY-3.0
  - - :permit
    - CC-BY-4.0
  - - :permit
    - CC0-1.0
  - - :permit
    - curl
  - - :permit
    - EFL-2.0
  - - :permit
    - FTL
  - - :permit
    - HPND-sell-variant
  - - :permit
    - ImageMagick
  - - :permit
    - ISC
  - - :permit
    - IJG
  - - :permit
    - HTMLTIDY
  - - :permit
    - JSON
  - - :permit
    - CNRI-Jython
  - - :permit
    - libtiff
  - - :permit
    - MS-PL
  - - :permit
    - MIT
  - - :permit
    - ICU
  - - :permit
    - X11
  - - :permit
    - MulanPSL-2.0
  - - :permit
    - OpenSSL
  - - :permit
    - PDDL-1.0
  - - :permit
    - PHP-3.0
  - - :permit
    - PostgreSQL
  - - :permit
    - PIL
  - - :permit
    - PSF-2.0
  - - :permit
    - PSF-2.1.1
  - - :permit
    - Ruby
  - - :permit
    - Scala
  - - :permit
    - OFL-1.1
  - - :permit
    - SLF4J
  - - :permit
    - blessing
  - - :permit
    - SMLNJ
  - - :permit
    - TCL
  - - :permit
    - NCSA
  - - :permit
    - Unlicense
  - - :permit
    - Vim
  - - :permit
    - W3C-19980720
  - - :permit
    - W3C
  - - :permit
    - W3C-20150513
  - - :permit
    - WTFPL
  - - :permit
    - Zlib
  - - :permit
    - ZPL-2.1
  - - :permit
    - Python-2.0
  - - :permit
    - Python Software Foundation License
  - - :permit
    - APACHEv2
  - - :permit
    - 0BSD
  - - :permit
    - BSD Zero Clause License
  - - :permit
    - Unicode-DFS-2015
  - - :permit
    - Unicode-DFS-2016
  - - :permit
    - Unicode Data Files
  - - :permit
    - WTFPL-2.0
  - - :permit
    - WT*PL
  - - :permit
    - libjpeg
  - - :permit
    - zlib-acknowledgement
  - - :permit
    - libpng
  - - :permit
    - bzip2
  - - :permit
    - Spencer-94
  - - :permit
    - BouncyCastle
  - - :permit
    - NTP
  - - :permit
    - BSD-2-Clause-FreeBSD
  - - :permit
    - BSD-3-Clause-Attribution
  - - :permit
    - BSD-1-Clause
  - - :permit
    - BSD-Source-Code
  - - :permit
    - EDL
  - - :permit
    - HDF5
  - - :permit
    - OLDAP-2.8
  - - :approve
    - "monorepo"
  - - :approve
    - "@nx/nx-darwin-arm64"
  - - :approve
    - "@nx/nx-linux-x64-gnu"
  - - :approve
    - "@nx/nx-linux-x64-musl"
  - - :approve
    - "axe-core"
  - - :approve
    - "jackspeak"
  - - :approve
    - "path-scurry"
  - - :approve
    - "@aws-lambda-powertools/commons"
  - - :approve
    - "@aws-lambda-powertools/logger"
  - - :approve
    - "@aws-lambda-powertools/metrics"
  - - :approve
    - "@aws-lambda-powertools/tracer"
  - - :approve
    - "asn1"
  - - :approve
    - "assert-plus"
  - - :approve
    - "aws-sign"
  - - :approve
    - "boom"
  - - :approve
    - "cheerio"
  - - :approve
    - "colors"
  - - :approve
    - "combined-stream"
  - - :approve
    - "cookie-jar"
  - - :approve
    - "cryptiles"
  - - :approve
    - "ctype"
  - - :approve
    - "delayed-stream"
  - - :approve
    - "esprima"
  - - :approve
    - "forever-agent"
  - - :approve
    - "hawk"
  - - :approve
    - "hoek"
  - - :approve
    - "http-signature"
  - - :approve
    - "json-stringify-safe"
  - - :approve
    - "jsonify"
  - - :approve
    - "oauth-sign"
  - - :approve
    - "request"
  - - :approve
    - "sntp"
  - - :approve
    - "tunnel-agent"
  - - :approve
    - "aenum"
  - - :approve
    - "wrapt"`,
};
